baseURL = "https://Opsys2015.github.io/"
languageCode = "ja"
title = "portfolio"
theme = "hugo-resume"
publishDir = "docs"

[params]
    firstName = "Yuki"
    lastName = "Otsuka"
    address = ""
    phone = ""
    contactNote = "フロントエンジニア" #used in QR code only
    profileImage = "img/me.png"
    email = "otsuka.opsys@gmail.com"
    description = "ITエンジニア(フリーランス)のポートフォリオ。30歳（未経験）からSIerを経て現在に至る。"
    favicon = "favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true
    showHistory = true
    showQr = false

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"


# [[params.handles]]
    # name = "LinkedIn"
    # link = "https://www.linkedin.com/in/edwardwebb/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/Opsys2015"

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/otsuka.opsys"
[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/positiveGuitar"

# [[params.handles]]
    # name = "Bitbucket"
    # link = "https://bitbucket.org/eddiewebb/"

# [[params.handles]]
#     name = "Stack Overflow"
#     link = "https://stackoverflow.com/users/story/82880"
#     icon = "stack-overflow" #optional icon attribute used for Font Awesome icons, otherwise the name is lowercased.

# [[params.handles]]
#     name = "Keybase"
#     link = "https://keybase.io/edwardawebb"
#     icon = "key" #optional icon attribute used for Font Awesome icons, otherwise the name is lowercased.

[params.google.analytics]
    trackerID = "UA-132838704-1"

[outputs] #only required for search
    home = ["HTML", "JSON"]
